.TH "Colidable" 3 "Thu Jan 12 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Colidable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Colidable\&.h>\fP
.PP
Inherited by \fBBackground\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBOverlapType\fP \fBOverlapDetect\fP (const SDL_Rect &, const \fBGvector\fP &)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBOverlapType\fP Colidable::OverlapDetect (const SDL_Rect &, const \fBGvector\fP &)\fC [pure virtual]\fP"

.PP
Implemented in \fBBackground\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
