.TH "Colidable" 3 "Wed Jan 18 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Colidable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Colidable\&.h>\fP
.PP
Inherited by \fBBackground\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBOverlapType\fP \fBOverlapDetect\fP (SDL_Rect *, SDL_Rect *)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBOverlapType\fP Colidable::OverlapDetect (SDL_Rect *, SDL_Rect *)\fC [pure virtual]\fP"

.PP
Implemented in \fBBackground\fP, and \fBBrick\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
