.TH "Drawable" 3 "Thu Jan 19 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drawable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Drawable\&.h>\fP
.PP
Inherited by \fBBackground\fP, and \fBSprite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDraw\fP (SDL_Renderer *)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void Drawable::Draw (SDL_Renderer *)\fC [pure virtual]\fP"

.PP
Implemented in \fBSprite\fP, \fBHero\fP, \fBBackground\fP, \fBBrick\fP, and \fBEnemy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
