.TH "src/Drawable.h" 3 "Thu Dec 15 2016" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Drawable.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_image\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'Gvector\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDrawable\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBOverlapType\fP { \fBOL_NO_COLLISION\fP =0, \fBOL_COLLISION\fP, \fBOL_SPECIAL\fP, \fBOL_DEADLY\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBOverlapType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOL_NO_COLLISION \fP\fP
.TP
\fB\fIOL_COLLISION \fP\fP
.TP
\fB\fIOL_SPECIAL \fP\fP
.TP
\fB\fIOL_DEADLY \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
