.TH "Gvector" 3 "Thu Jan 19 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gvector \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Gvector\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGvector\fP ()"
.br
.ti -1c
.RI "\fBGvector\fP (int a, int b)"
.br
.ti -1c
.RI "int \fBxDir\fP ()"
.br
.ti -1c
.RI "int \fByDir\fP ()"
.br
.ti -1c
.RI "int \fBxSpeed\fP ()"
.br
.ti -1c
.RI "int \fBySpeed\fP ()"
.br
.ti -1c
.RI "void \fBxZero\fP ()"
.br
.ti -1c
.RI "void \fByZero\fP ()"
.br
.ti -1c
.RI "void \fBxInvert\fP ()"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBGvector\fP &)"
.br
.ti -1c
.RI "\fBGvector\fP \fBoperator*\fP (const double)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Gvector::Gvector ()\fC [inline]\fP"

.SS "Gvector::Gvector (inta, intb)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBGvector\fP Gvector::operator* (const doublenumber)"

.SS "void Gvector::operator+= (const \fBGvector\fP &other)"

.SS "int Gvector::xDir ()"

.SS "void Gvector::xInvert ()"

.SS "int Gvector::xSpeed ()\fC [inline]\fP"

.SS "void Gvector::xZero ()\fC [inline]\fP"

.SS "int Gvector::yDir ()"

.SS "int Gvector::ySpeed ()\fC [inline]\fP"

.SS "void Gvector::yZero ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
