.TH "Hero" 3 "Wed Jan 18 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hero \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Hero\&.h>\fP
.PP
Inherits \fBSprite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHero\fP (\fBScene\fP *, int, int)"
.br
.ti -1c
.RI "\fB~Hero\fP ()"
.br
.ti -1c
.RI "void \fBGetKeys\fP (SDL_Event *)"
.br
.ti -1c
.RI "void \fBUpdate\fP (unsigned int, \fBColidable\fP **, int)"
.br
.ti -1c
.RI "void \fBDraw\fP (SDL_Renderer *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Hero::Hero (\fBScene\fP *context, intx, inty)"

.SS "Hero::~Hero ()"

.SH "Member Function Documentation"
.PP 
.SS "void Hero::Draw (SDL_Renderer *renderer)\fC [virtual]\fP"

.PP
Implements \fBDrawable\fP\&.
.SS "void Hero::GetKeys (SDL_Event *e)"

.SS "void Hero::Update (unsigned inttimePast, \fBColidable\fP **colideArray, intamountColidables)\fC [virtual]\fP"

.PP
Implements \fBSprite\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
