.TH "Level1" 3 "Thu Jan 19 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Level1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Level1\&.h>\fP
.PP
Inherits \fBLevel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevel1\fP (\fBScene\fP *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateMap\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Level1::Level1 (\fBScene\fP *context)"

.SH "Member Function Documentation"
.PP 
.SS "void Level1::CreateMap ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLevel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
