.TH "src/Scene.h" 3 "Wed Jan 11 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Scene.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_image\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'Drawable\&.h'\fP
.br
\fC#include 'UnMovable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBwindow_Height\fP   480"
.br
.ti -1c
.RI "#define \fBwindow_Width\fP   640"
.br
.ti -1c
.RI "#define \fBfps\fP   60"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define fps   60"

.SS "#define window_Height   480"

.SS "#define window_Width   640"

.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
