.TH "Scene" 3 "Thu Jan 19 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScene\fP ()"
.br
.ti -1c
.RI "\fB~Scene\fP ()"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.ti -1c
.RI "SDL_Texture * \fBLoadTexture\fP (std::string)"
.br
.ti -1c
.RI "SDL_Texture * \fBCreateMapTexture\fP (int, int)"
.br
.ti -1c
.RI "SDL_Renderer * \fBGetRenderer\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Scene::Scene ()"

.SS "Scene::~Scene ()"

.SH "Member Function Documentation"
.PP 
.SS "SDL_Texture * Scene::CreateMapTexture (intwidth, intheight)"

.SS "SDL_Renderer* Scene::GetRenderer ()\fC [inline]\fP"

.SS "SDL_Texture * Scene::LoadTexture (std::stringpath)"

.SS "void Scene::Run ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
