.TH "Scene" 3 "Thu Dec 15 2016" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScene\fP ()"
.br
.ti -1c
.RI "\fB~Scene\fP ()"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Scene::Scene ()"

.SS "Scene::~Scene ()"

.SH "Member Function Documentation"
.PP 
.SS "void Scene::Run ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
