.TH "Sprite" 3 "Wed Jan 18 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sprite\&.h>\fP
.PP
Inherits \fBDrawable\fP\&.
.PP
Inherited by \fBHero\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSprite\fP (std::string, \fBScene\fP *)"
.br
.ti -1c
.RI "\fB~Sprite\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (unsigned int, \fBColidable\fP **, int)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "SDL_Texture * \fBspriteSheet\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBleftArray\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBrightArray\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBbackArray\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBfrontArray\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBsrcRect\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBposRect\fP"
.br
.ti -1c
.RI "\fBGvector\fP \fBspeedVector\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sprite::Sprite (std::stringfile, \fBScene\fP *context)"

.SS "Sprite::~Sprite ()"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Sprite::Update (unsignedint, \fBColidable\fP **, int)\fC [pure virtual]\fP"

.PP
Implemented in \fBHero\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "SDL_Rect* Sprite::backArray\fC [protected]\fP"

.SS "SDL_Rect* Sprite::frontArray\fC [protected]\fP"

.SS "SDL_Rect* Sprite::leftArray\fC [protected]\fP"

.SS "SDL_Rect* Sprite::posRect\fC [protected]\fP"

.SS "SDL_Rect* Sprite::rightArray\fC [protected]\fP"

.SS "\fBGvector\fP Sprite::speedVector\fC [protected]\fP"

.SS "SDL_Texture* Sprite::spriteSheet\fC [protected]\fP"

.SS "SDL_Rect* Sprite::srcRect\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
