.TH "src/Sprite.h" 3 "Wed Jan 11 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Sprite.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Drawable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSprite\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
