.TH "Sprite" 3 "Wed Jan 11 2017" "sdlGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sprite\&.h>\fP
.PP
Inherits \fBDrawable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSprite\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (int)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "SDL_Rect * \fBleftArray\fP"
.br
.ti -1c
.RI "int \fBleftArrayLength\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBrightArray\fP"
.br
.ti -1c
.RI "int \fBrightArrayLength\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBbacktArray\fP"
.br
.ti -1c
.RI "int \fBbacktArrayLength\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBfronttArray\fP"
.br
.ti -1c
.RI "int \fBfrontArrayLength\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sprite::Sprite ()"

.SH "Member Function Documentation"
.PP 
.SS "void Sprite::Update (int)\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "SDL_Rect* Sprite::backtArray\fC [protected]\fP"

.SS "int Sprite::backtArrayLength\fC [protected]\fP"

.SS "int Sprite::frontArrayLength\fC [protected]\fP"

.SS "SDL_Rect* Sprite::fronttArray\fC [protected]\fP"

.SS "SDL_Rect* Sprite::leftArray\fC [protected]\fP"

.SS "int Sprite::leftArrayLength\fC [protected]\fP"

.SS "SDL_Rect* Sprite::rightArray\fC [protected]\fP"

.SS "int Sprite::rightArrayLength\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for sdlGame from the source code\&.
